// TODO header comments
// Created by justin on 2020-05-26.
// the random number generator must be seeded to ensure randomness
// Use srand(time(NULL)); to seed generator in calling program

#ifndef CONWAYLIFE_CONWAYLIFE_H
#define CONWAYLIFE_CONWAYLIFE_H



#include <memory>
#include <vector>
#include <iostream>
#include <cstdlib>
#include <time.h>
#include <string>

using namespace std;

const double PAUSE_TIME = 0.1;  // Pause time between printing frames

namespace justin_a_henley {
    class GameOfLife {
    public:
        // Constructors
        GameOfLife();  // Uses default game size
        GameOfLife(int width, int height, long maxTurns, int liveRate, char liveChar, char deadChar);  // Allows custom specs
        GameOfLife(int width, int height, long maxTurns, int liveRate); // Allows custom specs for an expected invisible game

        // Member functions

        int visibleLife();
        // Runs a single game of life, Displays the game to std::cout,
        // Precondition: The board has been generated by the constructor
        // Postcondition: Returns the number of turns the board survived, up to _maxTurns

        int invisibleLife();
        // Runs a single game of life, Displays the game to std::cout,
        // Precondition: The board has been generated by the constructor
        // Postcondition: Returns the number of turns the board survived, up to _maxTurns

    private:
        // Game specs, overridden by non-default constructor
        int _width = 20; // Default board width
        int _height = 20; // Default board height
        long _maxTurns = 1000;  // Maximum number of turns before a game ends
        int _liveRate = 50;  // Out of 100, percent of cells alive
        char _liveChar = '#';
        char _deadChar = ' ';

        // Empty game board list pointer
        vector<vector<char>> _prevBoard;
        vector<vector<char>> _gameBoard;

        // private member functions

        void generateBoard();
        // Generates the gameboard with the appropriate size and characters
        // Precondition: _gameBoard has not been given any values
        // Postcondition:  _gameBoard has been filled

        void printBoard();
        // Prints the current gameBoard
        // Precondition:  The board has been generated
        // Postcondition:  The board is printed to std::cout

        void checkBoard();
        // Generates the next frame of the gameboard
        // Precondition: _prevBoard and _gameBoard have both been generated
        // Postcondition: _prevBoard holds the last frame, and _gameBoard holds the new frame

        char checkCell(int yPos, int xPos);
        // Decides if a cell is alive or dead in the next frame
        // Precondition: yPos and xPos are valid locations within _prevBoard and _gameBoard
        // Postcondition: returns the state of the cell in the next frame

        bool boardAlive();
        // Checks if all cells have died on a board, rendering it dead
        // Precondition:  The _gameBoard has been given valid values
        // Postcondition: Returns true if any cell on the board is alive
    };
}


#endif //CONWAYLIFE_CONWAYLIFE_H
